services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: app
        tty: true
        ports:
            - "9000"
        depends_on:
            - mysql
        volumes:
            - .:/var/www
        networks:
            - blog_app

    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - blog_app

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: = ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            - blog_app

volumes:
    db:
networks:
    blog_app:
        driver: bridge
